apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWTRJRElPUXVGQnN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBek1EZ3hOelExTkRCYUZ3MHpOakF6TURVeE56VXdOREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURDNlc1VmxuNGRuc05OdVVURDdRSHdER2xLNkd4VW9XUWNtcXJwMlc5S2hDZW5ScWRrMFQ2K1BoSzgKVzhVSER6QzJabFZmUkxYMkYwUjV3WE1pRVRMeHZtbzdDR3VpN3JQUDBIZUplcXJsNnllMURIdUtWNFowbWIydQpEYXZLM0ZENUdQT3kvM2pJQ2lCK20vSHRzM0hRS29SZEZ2bU12VmF4aTMyQ2RoQUpSZVdnUVpvSk1nSXVrNkxwCmd3Sk12QUtSeFNSdkY5WEZBb0tRSnZkaHN0dU1pZy9XeThKdHlxaWx5RzFTYkF5S0JpbkwzNWlTbTkwTTl6NEgKNGVocFlKQmZRYnJzUERza3dUUFhzVmZDa1dVUmR0QXh4L0c1VlJSM0tiVW5raE43elJEVHE4N0xJQXExaTNzYQpSdWUra0J4OWFhckRUWW5PRFNSbDBtVXpOMmFaQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRSDVkV1FZSjlqUEp5eG0wQlQ4Q05xT282ZGREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkFHY2IxT01ZQwpZRldYRWZZcjFwNnhwclNpR0tFZHhlbldRMmFIeWZYRXFDYUdnMWpTRmdudzhBbjArZHluVnBWWmVLUzJuODdjCm1qOHNZOFRLb2xycHZ5Q3RFQXAyUlJqcnliY2h1TnlHWGU5N3N2YitldGlWLzI3cTcrcnVKNitIRzIrSE1HamsKL0xuSGdzRSttUVJuUlM3YTkrT2NVMTh0Y3dBc0VTQWcwZWYycUs4eW4xNURJcDhST0U5eDZibkFFZTJoektGQgpybWZ2LzQraUNncVozU2diMVZZU09JOWF5bityMlUrTFNwVDZENi9NcnVGeER4M3dIbUQwT2dkbGxac3E3MDN4ClVzV2xGWFY0RHBoNnJVNXVLYUdVeU1Tdm1odFZCeTVBV2xSUEZOcWVPc1hpK1pVTHJ0R0hjUWpwTlppNVVETmsKRXFkZUp4SkM3dDZKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://e1a6c908-7e22-40ce-96b1-c7a6d90997a9.ap-southeast-2-gw.linodelke.net:443
    name: lke577663

users:
  - name: lke577663-admin
    user:
      as-user-extra: {}
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNIeXZFa1I5ZWE4b1NwaU1HRjlzekZpbk9YN2c4dDZNY3BoQkJCMmJTX2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNXNxeGgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNjc3NmIzMzItZmYyNS00N2NhLWIxNWItNmVmZGYzOTYxOTQzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.oVti29nAObOo1xJ7LvODXdaEw3C1JoTH7aYfj9MLDT3LUP8PyonzvR3MfFO-ig6myiQwHCM8zaFfZoxQujU6gr5DuuJ-OO2wx0a_dbdESPmTB73UydvMxSgIwqjLFY-OYzmqZimKdlcgwWWcMmD78yhaytrJcuRZH0NaLFMejT_iRGyvFRw6JLJLElej45xXVtX7pzsWhmrEbCafa0SYwymnrmuHV3EQeV3BStt0vLS-Qy9RnXGDh45VTZ1sA8iBwH2eZFRunE43N1UKe50klev27oO6I9tbSXAhN4RAyKDCAX9MAV_27xqGx39gHeLkiOsMc6fDozgs8agIDl4wmg

contexts:
  - context:
      cluster: lke577663
      namespace: default
      user: lke577663-admin
    name: lke577663-ctx

current-context: lke577663-ctx
